pr: none
trigger:
  branches:
    include:
      - main

variables:
  - group: team-webb-general-params
  - group: webb-spoke1-ref
  - name: storageAccountName
    value: kthstyleref

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self
    path: github

  - task: NodeTool@0
    inputs:
      versionSource: "spec"
      versionSpec: 16.x

  - task: Npm@1
    displayName: Npm run ci
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: "custom"
      customCommand: "ci"

  - task: Npm@1
    displayName: Npm audit
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: "custom"
      customCommand: "audit"

  - task: Npm@1
    displayName: Npm run build
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: "custom"
      customCommand: "run build"

  - template: templates/static-web/upload-directory.yml@cet-iac
    parameters:
      sourceDir: build
      pathPrefix: kth-style
      storageAccountName: $(storageAccountName)

  - task: AzureCLI@2
    displayName: Change content-type of _about file
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az storage blob update \
        --auth-mode login \
        --container-name '$web' \
        --account-name ${{ variables.storageAccountName }} \
        --name 'kth-style' \
        --content-type 'application/json'
