pr: none
trigger:
  branches:
    include:
      - main
      # - web

variables:
  - group: team-webb-general-params
  - group: webb-spoke1-ref
  - name: storageAccountName
    value: kthstyledemoref

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: static-web-cache-control

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self
    path: github

  - task: NodeTool@0
    inputs:
      versionSource: "spec"
      versionSpec: 18.x

  - task: Npm@1
    displayName: Npm run ci
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: "custom"
      customCommand: "ci"

  #  - task: Npm@1
  #    displayName: Npm audit
  #    inputs:
  #      workingDir: "$(Pipeline.Workspace)/github"
  #      command: "custom"
  #      customCommand: "audit"

  - task: Npm@1
    displayName: Npm run build
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: "custom"
      customCommand: "run build"

  # Copy each relevant directory
  # - If we need to set cache control, we upload that directory separately


  # /style is the main path of the app
  - template: templates/static-web/upload-directory.yml@cet-iac
    parameters:
      sourceDir: "apps/style-web/dist/style"
      pathPrefix: "style"
      storageAccountName: $(storageAccountName)

  - template: templates/static-web/upload-directory.yml@cet-iac
    parameters:
      sourceDir: "apps/style-web/dist/style/assets"
      pathPrefix: "style/assets"
      storageAccountName: $(storageAccountName)
      cacheControl: "max-age=604800" # 7 days cache

  # /cm is the path that mocks /cm path in Cortina (to fetch blocks)
  - template: templates/static-web/upload-directory.yml@cet-iac
    parameters:
      sourceDir: "apps/style-web/dist/cm"
      pathPrefix: "cm"
      storageAccountName: $(storageAccountName)
