pr: none
trigger:
  branches:
    include:
      - main

variables:
  - group: team-webb-general-params
  - group: webb-spoke1-prod
  - name: storageAccountName
    value: kthstyledemoprod

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self
    path: github

  - task: NodeTool@0
    inputs:
      versionSource: "spec"
      versionSpec: 18.x

  - task: Npm@1
    displayName: Npm run ci
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: "custom"
      customCommand: "ci"

  #  - task: Npm@1
  #    displayName: Npm audit
  #    inputs:
  #      workingDir: "$(Pipeline.Workspace)/github"
  #      command: "custom"
  #      customCommand: "audit"

  - task: Npm@1
    displayName: Npm run build
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: "custom"
      customCommand: "run build"

  # /style is the main path of the app
  - template: templates/static-web/upload-directory.yml@cet-iac
    parameters:
      sourceDir: "apps/style-web/dist/style"
      pathPrefix: "style"
      storageAccountName: $(storageAccountName)

  # /cm is the path that mocks /cm path in Cortina (to fetch blocks)
  - template: templates/static-web/upload-directory.yml@cet-iac
    parameters:
      sourceDir: "apps/style-web/dist/cm"
      pathPrefix: "cm"
      storageAccountName: $(storageAccountName)
