# This pipeline deploys KTH Style in "e-lärande" subscription for testing
# purposes. Don't use this pipeline for anything else
trigger: none
pr: none

parameters:
  - name: generalParams
    type: string
    default: elarande-general-params

variables:
  - group: ${{ parameters.generalParams }}
  - group: elarande-spoke1-ref

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/static-web/infra.yml@cet-iac
    parameters:
      appName: "style-e-larande"
