# This pipeline publishes the `@kth/style` package to npm
pr: none
trigger:
  branches:
    include:
      - main

variables:
  - group: team-webb-general-params

steps:
  - checkout: self
    path: github

  - task: NodeTool@0
    inputs:
      versionSource: "spec"
      versionSpec: 20.x

  - task: Npm@1
    displayName: Run `npm ci` for `@kth/style`
    inputs:
      workingDir: "$(Pipeline.Workspace)/github/@kth/style"
      command: ci

  - task: Npm@1
    displayName: Run `npm run build` for `@kth/style`
    inputs:
      workingDir: "$(Pipeline.Workspace)/github/@kth/style"
      command: custom
      customCommand: run build

  - task: Npm@1
    displayName: Run `npm test` for `@kth/style`
    inputs:
      workingDir: "$(Pipeline.Workspace)/github/@kth/style"
      command: custom
      customCommand: test

  - task: Npm@1
    displayName: Publish `@kth/style` to npm
    inputs:
      workingDir: "$(Pipeline.Workspace)/github/@kth/style"
      command: publish
      publishRegistry: useExternalRegistry
      publishEndpoint: $(npmServiceConnection)
