# This pipeline performs checks for Pull Requests targetting main branch
trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main
  drafts: false

steps:
  - checkout: self
    path: github

  - task: NodeTool@0
    inputs:
      versionSource: "spec"
      versionSpec: 20.x

  - task: Npm@1
    displayName: Npm run ci
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: "custom"
      customCommand: "ci"

  - task: Npm@1
    displayName: Npm run build
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: "custom"
      customCommand: "run build"

  - task: Npm@1
    displayName: Npm run test
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: "custom"
      customCommand: "test"
