/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    examples: Example;
    components: Component;
    users: User;
  };
  globals: {};
}
export interface Example {
  id: string;
  title: string;
  content: {
    [k: string]: unknown;
  }[];
  createdAt: string;
  updatedAt: string;
}
export interface Component {
  id: string;
  title: string;
  purpose: string;
  'when-to-use': {
    [k: string]: unknown;
  }[];
  'when-not-to-use'?: {
    [k: string]: unknown;
  }[];
  'how-to-use': {
    [k: string]: unknown;
  }[];
  createdAt: string;
  updatedAt: string;
}
export interface User {
  id: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
