/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KthButton {
        "appearance": "primary" | "secondary" | "tertiary" | undefined;
    }
    interface KthTab {
    }
    interface KthTabsContent {
        "defaultTab": string;
    }
    interface KthTabsNavigation {
        "defaultTab": string;
    }
}
declare global {
    interface HTMLKthButtonElement extends Components.KthButton, HTMLStencilElement {
    }
    var HTMLKthButtonElement: {
        prototype: HTMLKthButtonElement;
        new (): HTMLKthButtonElement;
    };
    interface HTMLKthTabElement extends Components.KthTab, HTMLStencilElement {
    }
    var HTMLKthTabElement: {
        prototype: HTMLKthTabElement;
        new (): HTMLKthTabElement;
    };
    interface HTMLKthTabsContentElement extends Components.KthTabsContent, HTMLStencilElement {
    }
    var HTMLKthTabsContentElement: {
        prototype: HTMLKthTabsContentElement;
        new (): HTMLKthTabsContentElement;
    };
    interface HTMLKthTabsNavigationElement extends Components.KthTabsNavigation, HTMLStencilElement {
    }
    var HTMLKthTabsNavigationElement: {
        prototype: HTMLKthTabsNavigationElement;
        new (): HTMLKthTabsNavigationElement;
    };
    interface HTMLElementTagNameMap {
        "kth-button": HTMLKthButtonElement;
        "kth-tab": HTMLKthTabElement;
        "kth-tabs-content": HTMLKthTabsContentElement;
        "kth-tabs-navigation": HTMLKthTabsNavigationElement;
    }
}
declare namespace LocalJSX {
    interface KthButton {
        "appearance"?: "primary" | "secondary" | "tertiary" | undefined;
    }
    interface KthTab {
    }
    interface KthTabsContent {
        "defaultTab"?: string;
    }
    interface KthTabsNavigation {
        "defaultTab"?: string;
    }
    interface IntrinsicElements {
        "kth-button": KthButton;
        "kth-tab": KthTab;
        "kth-tabs-content": KthTabsContent;
        "kth-tabs-navigation": KthTabsNavigation;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kth-button": LocalJSX.KthButton & JSXBase.HTMLAttributes<HTMLKthButtonElement>;
            "kth-tab": LocalJSX.KthTab & JSXBase.HTMLAttributes<HTMLKthTabElement>;
            "kth-tabs-content": LocalJSX.KthTabsContent & JSXBase.HTMLAttributes<HTMLKthTabsContentElement>;
            "kth-tabs-navigation": LocalJSX.KthTabsNavigation & JSXBase.HTMLAttributes<HTMLKthTabsNavigationElement>;
        }
    }
}
