// @ts-check
import { transform } from "@svgr/core";
import fs from "node:fs";
import { createRequire } from "node:module";
import { format } from "prettier";

const iconList = {
  ExpandMore: "expand_more.svg",
};
const require = createRequire(import.meta.url);

let output = `
// This file is autogenerated with "scripts/generateIcons.mjs"
import * as React from "react";
import { SVGProps } from "react";
interface SVGRProps {
  title?: string;
  titleId?: string;
}
`;

for (const componentName in iconList) {
  const fileName = iconList[componentName];

  const input = fs.readFileSync(
    require.resolve(`@material-symbols/svg-400/outlined/${fileName}`),
    { encoding: "utf-8" }
  );

  output += await transform(
    input,
    {
      typescript: true,
      titleProp: true,
      template: (variables, { tpl }) => {
        return tpl`
        export const ${variables.componentName} = (${variables.props}) => (
          ${variables.jsx}
          );
          `;
      },
    },
    { componentName }
  );
}

fs.writeFileSync(
  new URL("../src/icons.tsx", import.meta.url),
  format(output, { filepath: "icons.tsx" })
);
